---
- name: install wget
  hosts: all
  tasks:
    - name: "Install wget" 
      package: name=wget state=present
    - include: incl.yml
    - name: Download file from a file path
      get_url:
        url: "{{ item }}"
        dest: /tmp/afilecopy.txt
      with_items:
        - https://www.w3.org/TR/PNG/iso_8859-1.txt
        - http://25.io/toau/audio/sample.txt
    - name: ansible create directory example
      file:
        path: /root/madhan/kumar/test
        state: directory
    - name: copying file from here to there
      copy:
        src: /home/ubuntu/ansi/a.txt
        dest: /root/madhan/kumar
    - name: copying python file from here to there
      copy:
        src: /home/ubuntu/ansi/sample.py
        dest: /root/madhan/kumar
    - name: running python file
      command: python  /root/madhan/kumar/sample.py
      register: out2
    - name: running python file
      command: python  /root/madhan/kumar/sample.py
      register: out
    - debug: var=out.stdout_lines
    - debug: var=out2.stdout_lines
    - name: copying python file from here to there
      copy:
        src: /home/ubuntu/ansi/sample2.py
        dest: /root/madhan/kumar
    - name: running python file
      command: python  /root/madhan/kumar/sample2.py this is sample of sys args
      register: out3
    - debug: var=out3.stdout_lines
